modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Upstream/issues"
[[mods]]
modId = "upstream"
version = "1.0"
displayName = "UpStream"
logoFile = "logo_text.png"
credits = "On curse"
authors = "Corgi Taco"
description = '''
A mod that adds endless and wider rivers
'''

[[dependencies.byg]]
modId = "forge"
mandatory = true
versionRange = "[34.1.42,)"
ordering = "NONE"
side = "BOTH"